"""Per-run cooperative cancellation (Phase 2).

`run_id` is generated by Node and passed via `X-Run-Id`. POST `/api/cancel` sets a flag;
streaming handlers poll `is_cancelled` between expensive stages.
"""
from __future__ import annotations

import asyncio
from typing import Dict, Optional

_events: Dict[str, asyncio.Event] = {}


def _ensure(run_id: str) -> asyncio.Event:
    ev = _events.get(run_id)
    if ev is None:
        ev = asyncio.Event()
        _events[run_id] = ev
    return ev


def request_cancel(run_id: str) -> bool:
    """Signal cancellation. Returns True if a run slot now exists (created or updated)."""
    rid = (run_id or "").strip()
    if not rid:
        return False
    _ensure(rid).set()
    return True


def is_cancelled(run_id: Optional[str]) -> bool:
    if not run_id:
        return False
    rid = run_id.strip()
    ev = _events.get(rid)
    return bool(ev and ev.is_set())


def clear_run(run_id: Optional[str]) -> None:
    rid = (run_id or "").strip()
    if rid:
        _events.pop(rid, None)
